export default {
    GET_MOVIES: 'GET_MOVIES',
    GET_CATEGORY: 'GET_CATEGORY',
    GET_MOVIE: 'GET_MOVIE',

    GET_ID_CATEGORY: 'GET_ID_CATEGORY',

    CLOSE_POPUP: 'CLOSE_POPUP',

    SET_LOADED: 'SET_LOADED',
    SET_LOADED_FILTER: 'SET_LOADED_FILTER'
}